import io
import re
import requests  
import streamlit as st
from dotenv import load_dotenv
from google import genai
from google.genai import types
from PIL import Image

load_dotenv()
client = genai.Client()

st.set_page_config(page_title="Multi-Model Gemini ChatBot", page_icon="🤖")
st.title("🤖 Advanced Multimodal Chatbot")
st.write("Welcome! Chat with me using text, or upload an image for me to look at.")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

def is_image_request(text: str) -> bool:
    pattern = r"\b(generate|create|draw|paint|show me an image of|make an image of)\b"
    return bool(re.search(pattern, text.lower()))

with st.sidebar:
    st.header("Upload Context")
    uploaded_file = st.file_uploader("Choose a picture", type=["jpg", "jpeg", "png"])

    if uploaded_file:
        preview_image = Image.open(uploaded_file)
        st.image(preview_image, caption="Uploaded Image Preview", use_container_width=True)


for message in st.session_state.chat_history:
    with st.chat_message(message["role"]):
        if message["type"] == "text":
            st.write(message["content"])
        elif message["type"] == "image":
            st.image(message["content"], caption="Generated by Assistant")

user_input = st.chat_input("Type your message here...")

if user_input:
    with st.chat_message("user"):
        st.write(user_input)
    st.session_state.chat_history.append({"role": "user", "type": "text", "content": user_input})
    
    if uploaded_file:
        with st.spinner("Analyzing your uploaded image..."):
            try:
                response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=[preview_image, user_input]
                )

                bot_text = response.text
                with st.chat_message("assistant"):
                    st.write(bot_text)
                st.session_state.chat_history.append({"role": "assistant", "type": "text", "content": bot_text})
            except Exception as e:
                error_msg = "Google Gemini servers are currently busy or unavailable. Please wait a minute and try again!"
                with st.chat_message("assistant"):
                    st.write(error_msg)
                st.session_state.chat_history.append({"role": "assistant", "type": "text", "content": error_msg})

    elif is_image_request(user_input):
        with st.spinner("Optimizing and generating your AI image..."):
            try:
                optimized_prompt = user_input
                if len(user_input) > 150:
                    compression_response = client.models.generate_content(
                        model="gemini-2.5-flash",
                        contents=f"Condense this image generation prompt into one short, dense, highly descriptive sentence under 25 words: {user_input}"
                    )
                    optimized_prompt = compression_response.text.strip()

                cleaned_prompt = re.sub(r'[^a-zA-Z0-9\s]', '', optimized_prompt)
                url_prompt = cleaned_prompt.replace(" ", "_")
                
                generation_url = f"https://image.pollinations.ai/p/{url_prompt}?width=1024&height=1024&nologo=true"
                
                img_response = requests.get(generation_url, timeout=60)
                
                if img_response.status_code == 200:
                    generated_pil_image = Image.open(io.BytesIO(img_response.content))

                    with st.chat_message("assistant"):
                        st.image(generated_pil_image, caption="Here is your custom generated image:")

                    st.session_state.chat_history.append({
                        "role": "assistant",
                        "type": "image",
                        "content": generated_pil_image
                    })
                else:
                    raise Exception("The generation cluster node is temporarily overloaded.")

            except Exception as e:
                friendly_error = "The free image generation server is experiencing heavy traffic or timed out. Please press 'Enter' on your input box to retry generating this scene!"
                with st.chat_message("assistant"):
                    st.write(friendly_error)
                st.session_state.chat_history.append({"role": "assistant", "type": "text", "content": friendly_error})

    else:
        with st.spinner("Gemini is thinking..."):
            try:
                response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=user_input
                )
                bot_text = response.text
                with st.chat_message("assistant"):
                    st.write(bot_text)
                st.session_state.chat_history.append({"role": "assistant", "type": "text", "content": bot_text})
            except Exception as e:
                error_msg = "Google Gemini servers are experiencing high demand right now. Let's try sending that text message again in a few moments!"
                with st.chat_message("assistant"):
                    st.write(error_msg)
                st.session_state.chat_history.append({"role": "assistant", "type": "text", "content": error_msg})